version: "2"

services:
  tf-smi1: # Preprocess and move data dump1 (from D:drive)
    image: chezhipower/smi_pipeline:latest
    container_name: 'smi_on_server1'
    ports:
      - "8886:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      - /mnt/ew18-00053_D/SMI:/tf/data
      - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      - /home/elan/sarcopenia_segmentation/final_CT:/tf/output
  tf-smi2: # Preprocess and move data dump2 (from /data/SMI_2)
    image: chezhipower/smi_pipeline:latest
    container_name: 'smi_on_server2'
    ports:
      - "8885:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      - /data/SMI_2:/tf/data
      - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      - /home/elan/sarcopenia_segmentation/final_CT:/tf/output   
  tf-smi3: # Preprocess and move data dump3 of exams  (from /data/SMI_2)
    image: chezhipower/smi_pipeline:latest
    container_name: 'smi_on_server3'
    ports:
      - "8883:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      - /data/SMI1_8pats:/tf/data
      - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      - /home/elan/sarcopenia_segmentation/final_CT:/tf/output   
  tf-pred: # Run predictio on the final data in (from /final_CT)
    image: chezhipower/smi_pipeline:latest
    container_name: 'smi_on_server3'
    #user: "1005:1006"
    ports:
      - "8884:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      - /home/elan/sarcopenia_segmentation/final_CT:/tf/data  
      - /home/elan/sarcopenia_segmentation/models:/tf/models   
      - /home/elan/sarcopenia_segmentation/output:/tf/output
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
  rpy: # Run Analysis on the final data in (from /final_CT)
    image: rpy2/jupyter_ds-ubuntu
    container_name: 'smi_rpy'
    ports:
      - "8898:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/home/jupyteruser/smipipeline
      - /home/elan/sarcopenia_segmentation/pickles:/home/jupyteruser/pickles
      - /home/elan/sarcopenia_segmentation/final_CT:/home/jupyteruser/data  
      - /home/elan/sarcopenia_segmentation/models:/home/jupyteruser/models   
      - /home/elan/sarcopenia_segmentation/output:/home/jupyteruser/output
  tf-mripred: # Container for MRI Segmentation on Lisa's data
    image: chezhipower/smi_pipeline:latest
    container_name: 'smi_mri'
    #user: "1005:1006"
    ports:
      - "8887:8888"
    volumes: 
      - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      - /home/elan/sarcopenia_segmentation/MRI_Lisa:/tf/data  
      - /home/elan/sarcopenia_segmentation/models:/tf/models   
      - /home/elan/sarcopenia_segmentation/output:/tf/output
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0


   # For Preprocessing
    # volumes: 
      # - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
      # - /mnt/ew18-00053_D/SMI:/tf/data1
      # - /data/SMI_2:/tf/data2
      # - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
      # - /home/elan/sarcopenia_segmentation/final_CT:/tf/output

  # # For Prediction
  #     - /home/elan/sarcopenia_segmentation/Muscle_Segmentation:/tf/smipipeline
  #     - /home/elan/sarcopenia_segmentation/models:/tf/models
  #     - /home/elan/sarcopenia_segmentation/pickles:/tf/pickles
  #     - /home/elan/sarcopenia_segmentation/final_CT:/tf/data
  # runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=0


    
