name: tensorflow
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu==1.8.0
  - imageio==2.5.0
  - Keras==2.2.4
  - matplotlib==3.1.0
  - nilearn==0.5.2
  - numpy==1.16.4
  - opencv-contrib-python==4.1.0.25
  - pandas==0.24.2
  - scikit-image==0.15.0
  - scikit-learn==0.21.2
  - tables==3.5.1
  - tables==3.5.1
  - opencv-contrib-python==4.1.0.25
